api-version: '${api_version}'
authors: ['TetraTheta']
load: POSTWORLD
main: io.github.tetratheta.compactresources.CompactResources
name: CompactResources
version: '${version}'
permissions:
  compactresources.compact:
    default: true
    description: Allow compacting items in the player's inventory
  compactresources.config:
    default: op
    description: View and edit CompactResources configuration values
  compactresources.reload:
    default: op
    description: Reload CompactResources configuration from the disk
