main: io.github.tetratheta.compactresources.CompactResources
api-version: '${api_version}'
load: POSTWORLD
name: CompactResources
authors: [ 'TetraTheta' ]
version: '${version}'
permissions:
  compactresources.compact:
    description: Allow compacting items in the player's inventory
    default: true
  compactresources.config.view:
    description: View CompactResources configuration values
    default: true
  compactresources.config.edit:
    description: Edit CompactResources configuration values
    default: op
  compactresources.reload:
    description: Reload CompactResources configuration from the disk
    default: op
